#! /bin/bash

i=1
CHIP=()
while [ $i -le 2 ]
do
   CHIP+=$(grep path_chip_$i: test/test_parameters.txt | awk '{for (k=2; k<=NF; k++) printf $k " "}')
   ((i++))
done

echo "Array inicial"
echo ${CHIP[@]}
echo LENGTH=${#CHIP[@]}

string="$CHIP"
echo "Cadena generada"
echo $string

read -a CHIP <<< $string


echo "Chip samples = q es array roto y su longitud"
echo ${CHIP[@]}
echo ${#CHIP[@]}

if [[ "$(declare -p CHIP)" =~ "declare -a" ]]; then
    echo array
else
    echo no array
fi

#BAMs:

i=1
BAMTF$i=()
while [ $i -le 1 ]
do
   j=1
   while [ $j -le 1 ]
   do
     BAMTF$i+=$(chip$i$j.bam)
     ((j++))
   done
   ((i++))
done

i=1
BAMCON$i=()
while [ $i -le 1 ]
do
   j=2
   while [ $j -le 2 ]
   do
     BAMCON$i+=$(chip$i$j.bam)
     ((j++))
   done
   ((i++))
done


macs2 callpeak -t $BAMTF$i -c $BAMCON$i  -f BAM --outdir . -n $EXP$i
