#! /bin/bash

##Parameters:
SAMPLE_DIR=$1
INSDIR=$2
SAMPLENAME=$3

echo ""
echo "========================="
echo "|PROCESSING $SAMPLENAME |" 
echo "========================="
echo ""

cd ${SAMPLE_DIR}

# Quality control

fastqc $SAMPLENAME.gz

# Mapping reads to reference genome
bowtie2 -x ../../../genome/index -U $SAMPLENAME.gz -S $SAMPLENAME.sam 2> mapping_file.txt & PID=$!

echo "Wait, principal Faragonda is managing the situation..."
printf "["
# While process is running...
while kill -0 $PID 2> /dev/null; do
    printf  "⚡"
    sleep 1
done
printf "] Finiquitao, maravillosa gestión de la Directora Faragonda !"

samtools sort -o $SAMPLENAME.bam $SAMPLENAME.sam
rm $SAMPLENAME.sam
samtools index $SAMPLENAME.bam

## Write on mapping file
mv mapping_file.txt ../../../results
echo "$SAMPLENAME:" >> ../../../results/mapping_values.txt

READS=$(grep reads ../../../results/mapping_file.txt | awk '{ print $1 }')
echo "Number of reads ="$READS >> ../../../results/mapping_values.txt

OVALIGN=$(grep overall ../../../results/mapping_file.txt | awk '{ print $1 }')
echo "Overall alignment ="$OVALIGN >> ../../../results/mapping_values.txt

rm ../../../results/mapping_file.txt

