#! /bin/bash

# Process.
SAMPLE=$1

#bowtie2 -x ../../../genome/index -U $SAMPLE -S  chip_1.sam

bowtie2 -x ../../../genome/index -U $SAMPLE -S  chip_1.sam  & PID=$! 

echo "Wait, principal Faragonda is managing the situation..."
printf "["
# While process is running...
while kill -0 $PID 2> /dev/null; do 
    printf  "⚡"
    sleep 1
done
printf "] done!"
