#! /bin/bash

##Parameters:
SAMPLE_DIR=$1
i=$2
NUMSAMPLES=$3
INSDIR=$4
SAMPLENAME=$5

echo ""
echo "========================="
echo "|PROCESSING $SAMPLENAME |" 
echo "========================="
echo ""

cd ${SAMPLE_DIR}

# Quality control

fastqc $SAMPLENAME.fq.gz

gzip -d $SAMPLENAME.fq.gz 

# Mapping reads to reference genome
bowtie2 -x ../../../genome/index -U $SAMPLENAME.fq -S $SAMPLENAME.sam 2> mapping_file.txt & PID=$!

echo "Wait, principal Faragonda is managing the situation..."
printf "["
# While process is running...
while kill -0 $PID 2> /dev/null; do
    printf  "⚡"
    sleep 1
done
printf "] Finiquitao, maravillosa gestión de la Directora Faragonda !"

mv mapping_file.txt ../../../results
samtools sort -o $SAMPLENAME.bam $SAMPLENAME.sam
rm $SAMPLENAME.sam
samtools index $SAMPLENAME.bam

## Write on mapping file
echo "$SAMPLENAME:" >> ../../../results/mapping_values

READS=$(grep reads ../../../results/mapping_file.txt | awk '{ print $1 }')
echo "Number of reads ="$READS >> ../../../results/mapping_values

OVALIGN=$(grep overall ../../../results/mapping_file.txt | awk '{ print $1 }')
echo "Overall alignment ="$OVALIGN >> ../../../results/mapping_values

##if [ $NUM_PROC -eq $NUMSAMPLES ]
##then
   #IGV
##fi


